ClassicPress/ClassicPress-APIs

.gitignore, v1-upgrade-generator/generate-upgrade-json.py, v1/checksums/index.php, v1/checksums/md5/index.php, v1/index.php
Looks to work properly from my quick testing. Closes #16.
=> Add checksums API

v1/migration/index.php
This patch updates supported WordPress migrations from:
5.5.4, 5.5.5
5.6, 5.6.1, 5.6.2, 5.6.3, 5.6.4
5.7, 5.7.1, 5.7.2
Tested using the core theme TwentyTwenty
It also starts the process of adding incompatible theme and plugin data to the API endpoint that will eventually be used in the Migration plugin.
=> Migration API update

v1/migration/index.php
Now that v1.3.0 stable has been released, and the automated nightly _migration_ build corresponding to this version has completed, we can have the migration plugin migrate users directly to v1.3.0.
See: https://github.com/ClassyBot/ClassicPress-nightly/releases/tag/1.3.0%2Bmigration.20210901
Closes https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/68.
=> Migrate to v1.3.0

v1/migration/index.php
This PR adds supported PHP version data to the migration API endpoint with the aim of stopping migration on WordPress sites that are using PHP version 8.0 and higher.
=> Add support PHP version data to the migration API endpoint

v1/migration/index.php
In local tests and apparently in a case on the forum, migration from 5.8.1 is successful, we should offer official support.
https://forums.classicpress.net/t/advanced-option-in-migration-plugin/3594
=> Support migrations for WordPress 5.8.1

bin/update-petitions-data.php
Per discussion at https://forums.classicpress.net/t/tags-on-petitions/3642 this PR changes the petitions API endpoint so that petitions will be excluded from the ClassicPress dashboard as soon as they are declined, rather than 1 week later when the petition's forum thread actually closes. This relies on the `declined` tag being added to declined petitions.
=> Exclude declined petitions from petitions list

v1/migration/index.php
I have manually tested migration from:
WordPress 5.9-RC1-52464
To the current migration release:
ClassicPress 1.3.1+migration.20211021
I saw no errors, admin screens for posts, plugins and themes are all still as expected and loading of several front end pages were all visually as expected.
=> Update endpoint for 5.9 and testing for presumed 6.0

.github/workflows/classicpress-release.yml, .github/workflows/wordpress-release.yml, v1/migration/index.php
Supersedes #36 as the origin repo for that PR ( https://github.com/mattyrob/ClassicPress-APIs ) has been deleted.
=> Create PR via workflow when ClassicPress is released

twemoji/update.sh
Update to commit and `gh-page` structure to enable Emoji 14 json creation
=> Enable v14 emoji json generation

v1-upgrade-generator/README.md, v1-upgrade-generator/generate-upgrade-json.py, v1-upgrade-generator/update.sh
These changes add the ClassicPress-v2 repository to enure the API is updated for V2.x.x nightly builds and any future releases.
=> Add v2 nightly repository in json generation

.github/workflows/classicpress-release.yml
The GitHub action for automatic detection of a new ClassicPress release are failing following an upstream branch name change.
This PR aims to address that and get the process working again.
=> Use renamed branch for PR creation

v1-upgrade-generator/README.md
The Python scripts located at `v1-upgrade-generator` have been updated for Python3, this PR updated the Readme to reflect those changes.
=> Update Readme for Python 3

v1-upgrade-generator/generate-upgrade-json.py
This PR aims to fix 2 issues in the generation of checksums for code releases.
Only the root files are having a checksum generated at the moment, this change ensure the script recurses through full git tree.
Since the introduction of a favicon in root, the script is failing due to Python encoding errors, this change encodes files accounting for non-text files.
=> Fix checksum generation

.github/workflows/wordpress-release.yml
This fix has been tested locally and fixed the same error as noted in local testing:
```
jq: error (at <stdin>:0): Cannot iterate over number (3600)
```
=> Fix: jq error appearing in WordPress release workflow

v1-upgrade-generator/generate-upgrade-json.py
MD5 hashes are being created in the current code including folders, this is incorrect, the MD5 should be created for files only.
This PR has been implemented manually on the Test and main API servers and fixes the above issue.
=> Skip folders when creating MD5 hashes

v1-upgrade-generator/generate-upgrade-json.py
During the release process for 2.0.0.-rc1 the following error eas seen on the API server when the JSON endpint script ran:
```
Traceback (most recent call last):
File "/var/www/html/ClassicPress-APIs-Test/v1-upgrade-generator/generate-upgrade-json.py", line 185, in <module>
if version < max_rel_ver:
TypeError: '<' not supported between instances of 'VersionInfo' and 'NoneType'`
```
This change fixed the error message.
=> Fix Python error when releasing pre-release code

.github/workflows/classicpress-release.yml, v1/migration/index.php
A GitHub action currently checks for new ClassicPress (and WordPress) releases and creates a PR automatically for the migration plugin API.
This PR updated the ClassicPress checks moving to the `v2` releases with the release of "Bella". This will alter behaviour of the migration plugin for new users and migrate site to `v2` of ClassicPress.
=> Use v2 nightly builds for migration checks

v1/core/importers/2.0/index.php, v1/index.php
See [WordPress/ClassicPress (WXR) Import Tool](https://github.com/ClassicPress/ClassicPress/issues/1339#top).
In ClassicPress v1 WordPress importer [must be installed manually](https://docs.classicpress.net/user-guides/using-classicpress/tools-import-screen/) as v0.7 is needed.
In ClassicPress v2 WordPress importer v0.8.2 (latest) works.
This PR adds a new endpoint so ClassicPress v2 can automatically install it from the "import" page.
=> Add importers endpoint for ClassicPress v2

.github/workflows/classicpress-release.yml, .github/workflows/wordpress-release.yml, v1/migration/index.php
This PR extend the API migration endpoint to deliver several linked migration options for a drop down in the migration plugin.
These additional options include the last major release of ClassicPress (currently 1.7.2) and the original WordPress versions forked for ClassicPress `v1` (WP 4.9.x) and ClassicPress `v2`(WP 6.2.x) - latest patch version of each respectively.
While making these changes, the GitHub actions in use have been updated to latest versions, process steps have been renamed slightly for clarify and step ordering has been updated for faster exit f there is no update.
=> Add linked migration options

v1/core/importers/2.0/index.php
As reported by @Guido07111975, the descriptions of installable / installed Importers at Tools > Import are not all translated.
This is because the core strings defined and translatable in the array here:
https://github.com/ClassicPress/ClassicPress/blob/bb10bc89a8bf0045f8c5360e9e157e57f6f9adfa/src/wp-admin/includes/import.php#L183
Don't match the strings server in the Import API:
https://github.com/ClassicPress/ClassicPress-APIs/blob/main/v1/core/importers/2.0/index.php
This PR aims to match these strings in the API response ensuring translation of these strings in core will work.
=> Match API descriptions to core strings for translation
